### ISSUE TITLE
请问大佬这个是需要在py环境运行的吧，可以打包成小工具exe吗

### ISSUE THREAD

**Issue by JCMakoto** [Liadrins/WeChat-Emoticon#1]

**Comment by Liadrins** [comment]
这个代码在py的idle中跑的贼6，可我也是py的萌新啊，所以咱们一起等真正的大佬过来把这个代码开发出exe的小程序吧(☆▽☆)

**Comment by JCMakoto** [comment]
> 这个代码在py的idle中跑的贼6，可我也是py的萌新啊，所以咱们一起等真正的大佬过来把这个代码开发出exe的小程序吧(☆▽☆)

好哒，谢谢大佬 _(:::з」∠)_
